### ISSUE TITLE
How to - 

### ISSUE THREAD

**Issue by PentesterGuy** [SandPox/android_kernel_kylepro#2]
Hello sir, 

Thanks for this kernel :) 

I have on samsung galaxy trend plus s7580 I want to install a custom kernel  ?
Please guide me how to do ? 

thanks 

Best Regards

**Comment by SandPox** [comment]
I'm just uploading the source code for who need them.

**Comment by PentesterGuy** [comment]
I need that sir please help me ? :)

Thanks

**Comment by SandPox** [comment]
I'm just leave a short summary of this:
First you'll need to have zImage (kernel file), you can get this by compile source on this repo
After you got zImage, unpack boot.img and replace zImage in that unpacked boot.img then repack boot.img
Then flash it, now cross your finger and hope for it boot, more details google pls, it's not that hard to find a tutorial about install custom kernel
