### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by PentesterGuy** [SandPox/android_kernel_kylepro#3]
Sorry @SandPox time in again i bother you :( 

But need help regarding this kernel ? 
is this the official kernel ? and does it work fine in galaxy trend plus (I mean all features )? 
By the way, With What verison of toolchain i have to use to compile this :) 

Please sir can you paste the compile command step by step :) 

Best Regards

**Comment by SandPox** [comment]
this is original open source kernel of s7580 on samsung open source site, I modified it to working with cm11 so don't expect it will run flawlessly on stock rom, more details about the changes here:
https://github.com/SandPox/android_kernel_kylepro/commits/master

work best with toolchain 4.6
https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/

after clone the source, edit this file
https://github.com/SandPox/android_kernel_kylepro/blob/master/Makefile
replace line 196 "CROSS_COMPILE	:=" with the toolchain path I give you above, remember the prefix "arm-eabi-" at the end

after that run
*make bcm21664_hawaii_ss_kylepro_rev00_defconfig
*make menuconfig (this is optional if you want to modify the kernel config)
*make

you'll have to wait it to finish compiling and if no error happens it will tell you 
arch/arm/boot/zImage is ready, go to arch/arm/boot/ and grab file zImage, it's your compiled kernel, now you'll have to find a way to unpack boot.img and replace it in there, I'm just maintain the kernel

**Comment by PentesterGuy** [comment]
Thanks sir :) 
But what about the official kernel from samsung website how we should compile ? for galaxy trend plus s7580 ?  please if you can do it step by step :) 
and i want to patch this at which part i should do please help :) 

thanks

**Comment by SandPox** [comment]
compile pretty same, the patch you must do it yourself, it cannot work-out-of-box after patch, I don't even think that patch will success, you'll have to fix it your self

**Comment by PentesterGuy** [comment]
Ok thanks
